# Generated by Django 3.1.2 on 2025-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_business_seats',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_economy_seats',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_first_seats',
            field=models.IntegerField(default=10),
        ),
    ]
