# Generated by Django 3.1.2 on 2025-12-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20251117_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='total_business_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='total_economy_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='total_first_seats',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('price', models.FloatField()),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flight.flight')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='selected_seats',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='flight.Seat'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['flight', 'status'], name='flight_seat_flight__8d5618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight', 'seat_number')},
        ),
    ]
