"""
Django settings for capstone project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect deployment platform
IS_GAE = os.environ.get('GAE_APPLICATION', None) is not None
IS_RENDER = os.environ.get('RENDER', None) is not None

# Amadeus Flight API Configuration
AMADEUS_CLIENT_ID = os.environ.get('API_Key', '')
AMADEUS_CLIENT_SECRET = os.environ.get('API_Secret', '')
AMADEUS_ENABLED = os.environ.get('AMADEUS_ENABLED', 'true').lower() == 'true'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '=k3z-^1ov_hy5y%ebw(2e-npk@$#!(c8ix=+7so*hmw9m0c52*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not (IS_GAE or IS_RENDER)

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.appspot.com',  # Google App Engine
    '.run.app',      # Cloud Run
    '.onrender.com', # Render
]

# Add CSRF trusted origins for production platforms
if IS_GAE:
    CSRF_TRUSTED_ORIGINS = ['https://*.appspot.com']
elif IS_RENDER:
    CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'flight'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'capstone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if IS_GAE:
    # Cloud SQL PostgreSQL connection via Unix socket
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'flightdb',
            'USER': 'postgres',
            'PASSWORD': 'FlightApp2025!',
            'HOST': '/cloudsql/flight-app-2025:asia-south1:flight-db',
        }
    }
elif IS_RENDER:
    # Render PostgreSQL via DATABASE_URL (manual parsing for Django 3.1 compatibility)
    DATABASE_URL = os.environ.get('DATABASE_URL', '')
    if DATABASE_URL:
        db_url = urlparse(DATABASE_URL)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_url.path[1:],  # Remove leading slash
                'USER': db_url.username,
                'PASSWORD': db_url.password,
                'HOST': db_url.hostname,
                'PORT': db_url.port or 5432,
                'OPTIONS': {
                    'sslmode': 'require',  # Required for Neon PostgreSQL
                },
            }
        }
    else:
        # Fallback to SQLite if no DATABASE_URL
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Local development uses file-based SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')


AUTH_USER_MODEL = 'flight.User'

# DEBUG = False


# ============================================
# Email Configuration (SendGrid)
# ============================================
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')

if SENDGRID_API_KEY:
    # Use SendGrid for real email delivery
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'  # This is literally the string 'apikey'
    EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
    DEFAULT_FROM_EMAIL = 'Flight Bookings <hasratmd697@gmail.com>'
else:
    # Fallback to console for development without SendGrid
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Flight Bookings <hasratmd697@gmail.com>'
